### ISSUE TITLE
missing weekday computation in adjust(...)

### ISSUE THREAD

**Issue by udoklein** [udoklein/dcf77#26]
Joachim Grimm reported, that void adjust(...) fails to recompute the weekday. The issue affects the examples simple_clock_with_timezone_support as well as the swiss_army_debug_helper.

**Comment by udoklein** [comment]
Three possible solutions:

1) assume weekday is correct and apply proper delta to it
2) convert time into internal format and let the library computer the weekday
3) directly compute the weekday from the date

I will ponder it a little more what would be the best approach.

**Comment by udoklein** [comment]
Fixed with this release: https://github.com/udoklein/dcf77/tree/v3.2.2
(commit 14c6389f4f8e594eee036f34bc85c29e889fbad2)

**Comment by Jo-Achim** [comment]
Thank you, Udo.
