### ISSUE TITLE
Redundant Code in dcf77.h

### ISSUE THREAD

**Issue by nameoftherose** [udoklein/dcf77#35]
It seems to me that lines [2118 - 2120](https://github.com/udoklein/dcf77/blob/master/dcf77.h#L2118) in dcf77.h are redundant as function `BCD::bcd_t DCF77_Encoder::get_bcd_weekday()` ([line 800 dcf77.cpp](https://github.com/udoklein/dcf77/blob/master/dcf77.cpp#L800)) has already adjusted `weekday.val`.
But I am be missing something and anyway it is without consequences.

**Comment by udoklein** [comment]
Yes, this is redundant. I will fix it with v3.3.2

**Comment by udoklein** [comment]
Fixed: https://github.com/udoklein/dcf77/tree/v3.3.2
