### ISSUE TITLE
Possible to compile on ESP8266?

### ISSUE THREAD

**Issue by sanchosk** [udoklein/dcf77#38]
Is it possible to compile this code on ESP8266?
Can someone suggest what changes do I need to do in order to make it work?
I bought the module and want to make a Wifi clock server in an area where no internet connection is allowed.
Thanks in advance.

**Comment by udoklein** [comment]
Have a look at "architectures" here: https://github.com/udoklein/dcf77/blob/master/library.properties

**Comment by udoklein** [comment]
I suggest to go for a some cheap Linux system (e.g. Raspi) plus my Meinberg emulator: https://blog.blinkenlight.net/experiments/dcf77/meinberg-emulator/ntpd-configuration/

**Comment by ziotibia81** [comment]
@sanchosk could you test PR #49 ?

Bye
