### ISSUE TITLE
DCF77_Scope.ino bug - missing volatile declaration

### ISSUE THREAD

**Issue by 6v6gt-duino** [udoklein/dcf77#42]
DCF77_Scope.ino (bug)

The variable declared here:

`boolean samples_pending = false;`

is set in an ISR and used in the loop().
It should be declared additionally as volatile.

I discovered this while debugging the sketch on an ATtiny1614. I'm guessing, that in this case, the compiler has done some aggressive optimisation and kept the value in a register in the loop() code so it always behaves as if the value is false.

**Comment by udoklein** [comment]
Fixed with the newest release https://github.com/udoklein/dcf77/releases/tag/v3.3.7 . Thanks for finding this one.
